const $=s=>document.querySelector(s),msg=$('#message'),stage=$('#stage'),progress=$('#progress');let timer,index=0,words=[],stream,recognition;
const clips={'hello':'videos/hello.mp4','thanks':'videos/thanks.mp4','yes':'videos/yes.mp4','no':'videos/no.mp4','مرحبا':'videos/hello.mp4','شكرا':'videos/thanks.mp4'};
function clean(){return msg.value.trim().replace(/[،,؟!?]/g,'').split(/\s+/).filter(Boolean)}
function show(){if(index>=words.length){progress.textContent='اكتمل العرض';return}const w=words[index++],src=clips[w.toLowerCase()];stage.innerHTML=src?`<div><video class="clip" src="${src}" controls autoplay muted playsinline></video><div>${w}</div></div>`:`<div><div class="word">${w}</div><small>أضف فيديو ASL لهذه الكلمة داخل videos/</small></div>`;progress.textContent=`الكلمة ${index} من ${words.length}: ${w}`}
$('#play').onclick=()=>{words=clean();if(!words.length){progress.textContent='اكتب رسالة أولاً';return}clearInterval(timer);index=0;show();timer=setInterval(()=>index<words.length?show():clearInterval(timer),2600)};
$('#clear').onclick=()=>{msg.value='';stage.textContent='ستظهر الكلمة أو مقطع الفيديو هنا';progress.textContent='جاهز'};
$('#speak').onclick=()=>{if(msg.value.trim()){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(msg.value);u.lang=$('#lang').value;speechSynthesis.speak(u)}};
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){recognition=new SR;recognition.continuous=true;recognition.interimResults=true;recognition.onstart=()=>$('#recognition').textContent='يستمع الآن...';recognition.onend=()=>$('#recognition').textContent='تم إيقاف الاستماع';recognition.onerror=e=>$('#recognition').textContent='خطأ: '+e.error;recognition.onresult=e=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript;$('#live').value=t}}$('#listen').onclick=()=>{if(recognition){recognition.lang=$('#lang').value;recognition.start()}};$('#stop').onclick=()=>recognition&&recognition.stop();
$('#cameraOn').onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});$('#camera').srcObject=stream;$('#cameraText').textContent='تم تشغيل الكاميرا. اربط نموذج ASL هنا لترجمة الحركات.'}catch(e){$('#cameraText').textContent='تعذر تشغيل الكاميرا: '+e.message}};$('#cameraOff').onclick=()=>{if(stream)stream.getTracks().forEach(t=>t.stop());$('#camera').srcObject=null};
function links(){const text=encodeURIComponent(msg.value);$('#wa').href='https://wa.me/?text='+text;$('#messenger').href='https://www.facebook.com/dialog/send?link='+encodeURIComponent(location.href)+'&app_id=0&redirect_uri='+encodeURIComponent(location.href)}links();msg.oninput=links;$('#share').onclick=async()=>{if(navigator.share)await navigator.share({title:'Ahmed-Deaf-11',text:msg.value||'رسالة تواصل للصم'});else alert('استخدم أزرار المشاركة أو انسخ الرسالة.')};
